### ISSUE TITLE
自动获取最新版的方法

### ISSUE THREAD

**Issue by dustofsoul** [SayaBear/AFU#1]
在下载ASF之前加一行
```
ASF_ver=$(wget  -qO- https://api.github.com/repos/JustArchi/ArchiSteamFarm/releases | grep -o '"tag_name": ".*"' |head -n 1| sed 's/"//g' | sed 's/tag_name: //g'
)
```
然后把ASF下载地址改成`https://github.com/JustArchi/ArchiSteamFarm/releases/download/${ASF_ver}/ASF-linux-x64.zip`就行了

**Comment by SayaBear** [comment]
Hello，写死版本号的原因是有的时候json配置文件的格式跟不上更新，我个人也没有时间一直盯着这套code修改，所以在没有重要更新之前先用着3.3.0.3版本了

**Comment by zhz1237ok** [comment]
亲测4.1.2.0是继承老的json配置文件的，我一直跟着更新，没有问题
是时候更新一次版本号了
https://github.com/JustArchiNET/ArchiSteamFarm/releases/download/4.1.2.0/ASF-linux-x64.zip
